# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: [build_rpm]
  push:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: ls before
        run: |
          ls -l
      - name: build rpm el8
        id: build_rpm
        env:
          SPEC_FILE: fake.spec
          RELEASE_TAG: v0.0.1
          RELEASE_GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        uses: docker://yoannguion/rpmbuilder
      - name: ls after
        run: |
          ls -l
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        with:
          tag_name: v0.0.1
          release_name: Release v0.0.1
          draft: false
          prerelease: false
      - name: Upload Release Assets
        id: upload-release-assets
        env:
          RELEASE_ASSETS_UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}
          RELEASE_GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        uses: docker://yoannguion/copy-rpms-to-release
      - name: ls after
        run: |
          ls -l
      - name: Upload Release Assets to packagecloud.io
        id: upload-release-assets-packagecloud-io
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        with:
          args: /pkgcloud-push yoannguion/el8 fake-0.0.1-0.el8.x86_64.rpm
        uses: docker://yoannguion/pkgcloud
